<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Admin\**" />
    <Compile Remove="Models\CareerAdvisor\**" />
    <Compile Remove="Models\Employer\**" />
    <Content Remove="Models\Admin\**" />
    <Content Remove="Models\CareerAdvisor\**" />
    <Content Remove="Models\Employer\**" />
    <EmbeddedResource Remove="Models\Admin\**" />
    <EmbeddedResource Remove="Models\CareerAdvisor\**" />
    <EmbeddedResource Remove="Models\Employer\**" />
    <None Remove="Models\Admin\**" />
    <None Remove="Models\CareerAdvisor\**" />
    <None Remove="Models\Employer\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Admin\" />
    <Folder Include="Controllers\Employer\" />
    <Folder Include="Controllers\CareerAdvisor\" />
    <Folder Include="Migrations\" />
    <Folder Include="Views\Admin\" />
    <Folder Include="Views\CareerAdvisor\" />
    <Folder Include="Views\Employer\" />
    <Folder Include="wwwroot\uploads\resumes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
