const AWSXRay = require('aws-xray-sdk-core');
const sql = require('mssql');
const { S3Client, PutObjectCommand, GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const { SNSClient, PublishCommand } = require('@aws-sdk/client-sns');

const s3Client = AWSXRay.captureAWSv3Client(new S3Client({}));
const snsClient = AWSXRay.captureAWSv3Client(new SNSClient({}));

const BUCKET = process.env.S3_BUCKET;
const TOPIC_ARN = process.env.SNS_TOPIC_ARN;

const dbConfig = {
  server: process.env.DB_SERVER,
  database: process.env.DB_NAME,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  port: parseInt(process.env.DB_PORT || '1433', 10),
  options: { encrypt: true, trustServerCertificate: true },
  pool: { max: 5, min: 0, idleTimeoutMillis: 30000 },
  connectionTimeout: 15000,
  requestTimeout: 30000
};

let poolPromise = null;
function getPool() {
  if (!poolPromise) {
    poolPromise = new sql.ConnectionPool(dbConfig).connect().catch(err => {
      poolPromise = null;
      throw err;
    });
  }
  return poolPromise;
}

function line(char = '=', n = 60) {
  return char.repeat(n);
}

function fmtDate(d) {
  if (!d) return '-';
  return new Date(d).toISOString().replace('T', ' ').substring(0, 16);
}

async function scalar(pool, query) {
  const r = await pool.request().query(query);
  return r.recordset[0].v;
}

async function buildEmploymentReport(pool) {
  const [
    totalUsers, activeUsers, suspendedUsers,
    totalEmployers, approvedEmployers, pendingEmployers, rejectedEmployers,
    totalJobs, openJobs, draftJobs, closedJobs, totalApplications
  ] = await Promise.all([
    scalar(pool, "SELECT COUNT(*) AS v FROM Users"),
    scalar(pool, "SELECT COUNT(*) AS v FROM Users WHERE Status = 'Active'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM Users WHERE Status = 'Suspended'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM EmployerProfiles"),
    scalar(pool, "SELECT COUNT(*) AS v FROM EmployerProfiles WHERE VerificationStatus = 'Approved'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM EmployerProfiles WHERE VerificationStatus = 'Pending'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM EmployerProfiles WHERE VerificationStatus = 'Rejected'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM JobVacancies"),
    scalar(pool, "SELECT COUNT(*) AS v FROM JobVacancies WHERE Status = 'Open'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM JobVacancies WHERE Status = 'Draft'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM JobVacancies WHERE Status = 'Closed'"),
    scalar(pool, "SELECT COUNT(*) AS v FROM JobApplications")
  ]);

  const out = [];
  out.push('EMPLOYMENT STATISTICS REPORT');
  out.push('Generated: ' + fmtDate(new Date()) + ' UTC');
  out.push('Generated by: ddac-report-generator (AWS Lambda)');
  out.push(line());
  out.push('');
  out.push('USER ACTIVITY');
  out.push('Total users: ' + totalUsers);
  out.push('Active: ' + activeUsers);
  out.push('Suspended: ' + suspendedUsers);
  out.push('');
  out.push('EMPLOYER VERIFICATION');
  out.push('Total employers: ' + totalEmployers);
  out.push('Approved: ' + approvedEmployers);
  out.push('Pending: ' + pendingEmployers);
  out.push('Rejected: ' + rejectedEmployers);
  out.push('');
  out.push('EMPLOYMENT STATISTICS');
  out.push('Total job postings: ' + totalJobs);
  out.push('Open: ' + openJobs);
  out.push('Draft: ' + draftJobs);
  out.push('Closed: ' + closedJobs);
  out.push('Total applications submitted: ' + totalApplications);
  out.push('');

  return {
    content: out.join('\n'),
    fileName: 'EmploymentReport_' + Date.now() + '.txt'
  };
}

async function buildUserReport(pool, userId) {
  const userRes = await pool.request()
    .input('id', sql.Int, userId)
    .query('SELECT * FROM Users WHERE UserID = @id');

  if (userRes.recordset.length === 0) {
    throw new Error('User ' + userId + ' not found');
  }
  const user = userRes.recordset[0];

  const out = [];
  out.push('USER REPORT');
  out.push('Generated: ' + fmtDate(new Date()) + ' UTC');
  out.push('Generated by: ddac-report-generator (AWS Lambda)');
  out.push(line());
  out.push('');
  out.push('BASIC INFO');
  out.push('User ID: ' + user.UserID);
  out.push('Name: ' + user.FullName);
  out.push('Email: ' + user.Email);
  out.push('Phone: ' + (user.PhoneNumber || '-'));
  out.push('Role: ' + user.Role);
  out.push('Status: ' + user.Status);
  out.push('Joined: ' + fmtDate(user.CreatedDate));
  out.push('');

  if (user.Role === 'JobSeeker') {
    const profile = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM JobSeekerProfiles WHERE JobSeekerID = @id')).recordset[0];
    out.push('JOB SEEKER PROFILE');
    out.push('Career Goal: ' + (profile?.CareerGoal || '-'));
    out.push('Bio: ' + (profile?.Bio || '-'));
    out.push('Preferred Location: ' + (profile?.PreferredLocation || '-'));
    out.push('Resume URL: ' + (profile?.ResumeURL || '-'));
    out.push('Accommodation Needs: ' + (profile?.AccommodationNeeds || '-'));
    out.push('');

    const skills = (await pool.request().input('id', sql.Int, userId).query(
      'SELECT s.SkillName, js.SkillLevel FROM JobSeekerSkills js ' +
      'JOIN Skills s ON js.SkillID = s.SkillID WHERE js.JobSeekerID = @id')).recordset;
    out.push('SKILLS (' + skills.length + ')');
    skills.forEach(s => out.push('  - ' + s.SkillName + ' (' + s.SkillLevel + ')'));
    out.push('');

    const quals = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM Qualifications WHERE JobSeekerID = @id')).recordset;
    out.push('QUALIFICATIONS (' + quals.length + ')');
    quals.forEach(q => out.push('  - ' + q.QualificationName + ', ' + q.Institution + ' (' + q.CompletionYear + ')'));
    out.push('');

    const apps = (await pool.request().input('id', sql.Int, userId).query(
      'SELECT j.JobTitle, a.ApplicationDate, a.Status, a.ResumeURL, a.CoverLetter ' +
      'FROM JobApplications a JOIN JobVacancies j ON a.JobID = j.JobID ' +
      'WHERE a.JobSeekerID = @id ORDER BY a.ApplicationDate DESC')).recordset;
    out.push('JOB APPLICATIONS (' + apps.length + ')');
    apps.forEach(a => {
      out.push('  - ' + a.JobTitle + ' | Applied ' + fmtDate(a.ApplicationDate) + ' | ' + a.Status);
      out.push('    Resume: ' + (a.ResumeURL || '-'));
      out.push('    Cover Letter: ' + (a.CoverLetter || '-'));
    });
    out.push('');

  } else if (user.Role === 'Employer') {
    const profile = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM EmployerProfiles WHERE EmployerID = @id')).recordset[0];
    out.push('COMPANY PROFILE');
    out.push('Company Name: ' + (profile?.CompanyName || '-'));
    out.push('Industry: ' + (profile?.Industry || '-'));
    out.push('Description: ' + (profile?.CompanyDescription || '-'));
    out.push('Address: ' + (profile?.Address || '-'));
    out.push('Website: ' + (profile?.Website || '-'));
    out.push('Verification Status: ' + (profile?.VerificationStatus || '-'));
    out.push('');

    const jobs = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM JobVacancies WHERE EmployerID = @id ORDER BY PostedDate DESC')).recordset;
    out.push('JOB POSTINGS (' + jobs.length + ')');
    jobs.forEach(j => {
      out.push('  - ' + j.JobTitle + ' | ' + j.Location + ' | ' + j.EmploymentType +
               ' | Posted ' + fmtDate(j.PostedDate) + ' | ' + j.Status);
      out.push('    Description: ' + j.Description);
      out.push('    Accessibility: ' + j.AccessibilityFeatures);
      out.push('    Accommodations: ' + j.AccommodationsAvailable);
    });
    out.push('');

  } else if (user.Role === 'CareerAdvisor') {
    const profile = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM CareerAdvisorProfiles WHERE AdvisorID = @id')).recordset[0];
    out.push('ADVISOR PROFILE');
    out.push('Specialisation: ' + (profile?.Specialisation || '-'));
    out.push('Qualification: ' + (profile?.Qualification || '-'));
    out.push('Experience: ' + (profile?.ExperienceYears ?? '-') + ' years');
    out.push('Bio: ' + (profile?.Bio || '-'));
    out.push('');

    const resources = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM CareerResources WHERE AdvisorID = @id ORDER BY PublishedDate DESC')).recordset;
    out.push('PUBLISHED RESOURCES (' + resources.length + ')');
    resources.forEach(r => {
      out.push('  - ' + r.Title + ' | ' + r.Category + ' | Published ' + fmtDate(r.PublishedDate) + ' | ' + r.Status);
      out.push('    Description: ' + r.Description);
      out.push('    URL: ' + r.ContentURL);
    });
    out.push('');

  } else if (user.Role === 'Admin') {
    const anns = (await pool.request().input('id', sql.Int, userId)
      .query('SELECT * FROM Announcements WHERE AdminID = @id ORDER BY PublishedDate DESC')).recordset;
    out.push('ANNOUNCEMENTS POSTED (' + anns.length + ')');
    anns.forEach(a => {
      out.push('  - ' + a.Title + ' | Published ' + fmtDate(a.PublishedDate) + ' | ' + a.Status);
      out.push('    Content: ' + a.Content);
    });
    out.push('');
  }

  const safeName = String(user.FullName).replace(/[^a-zA-Z0-9]+/g, '_');
  return {
    content: out.join('\n'),
    fileName: 'UserReport_' + safeName + '_' + Date.now() + '.txt'
  };
}

async function processJob(job) {
  const pool = await getPool();

  const report = job.ReportType === 'User'
    ? await buildUserReport(pool, job.UserID)
    : await buildEmploymentReport(pool);

  const key = 'reports/' + report.fileName;

  await s3Client.send(new PutObjectCommand({
    Bucket: BUCKET,
    Key: key,
    Body: report.content,
    ContentType: 'text/plain; charset=utf-8',
    Metadata: {
      requestid: job.RequestID || 'n/a',
      reporttype: job.ReportType,
      requestedby: String(job.RequestedBy || 'unknown')
    }
  }));

  const downloadUrl = await getSignedUrl(
    s3Client,
    new GetObjectCommand({
      Bucket: BUCKET,
      Key: key,
      ResponseContentDisposition: 'attachment; filename="' + report.fileName + '"'
    }),
    { expiresIn: 3600 }
  );

  if (TOPIC_ARN) {
    await snsClient.send(new PublishCommand({
      TopicArn: TOPIC_ARN,
      Subject: ('Report ready: ' + report.fileName).substring(0, 100),
      Message:
        `Your ${job.ReportType} report has been generated.\n\n` +
        `File: ${report.fileName}\n` +
        `Requested by: ${job.RequestedBy}\n` +
        `Request ID: ${job.RequestID}\n\n` +
        `Download (link valid for 1 hour):\n${downloadUrl}\n`,
      MessageAttributes: {
        eventType: { DataType: 'String', StringValue: 'REPORT_READY' }
      }
    }));
  }

  console.log('Report written to s3://' + BUCKET + '/' + key);
  return key;
}

exports.handler = async (event) => {
  const failures = [];

  for (const record of event.Records || []) {
    try {
      const job = JSON.parse(record.body);
      console.log('Processing report job', job.RequestID, job.ReportType);
      await processJob(job);
    } catch (err) {
      console.error('Failed to process message', record.messageId, err);
      failures.push({ itemIdentifier: record.messageId });
    }
  }

  return { batchItemFailures: failures };
};
